### ISSUE TITLE
brew gem install doesn't also install `rexml`

### ISSUE THREAD

**Issue by kjaymiller** [ttscoff/searchlink#10]
```sh
<internal:/opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- rexml/document (LoadError)
        from <internal:/opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /opt/homebrew/Cellar/gem-searchlink/2.3.66/gems/searchlink-2.3.66/lib/searchlink.rb:7:in `<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /opt/homebrew/Cellar/gem-searchlink/2.3.66/gems/searchlink-2.3.66/bin/searchlink:8:in `<top (required)>'
        from /opt/homebrew/bin/searchlink:6:in `load'
        from /opt/homebrew/bin/searchlink:6:in `<main>'
```

When I try the `echo '!brettterpstra.com project searchlink' | searchlink` or even a generic search I get this message.

Things I've tried:

- `sudo brew gem install searchlink`
-  `sudo brew gem install rexml`

**Comment by kjaymiller** [comment]
for completion... 

I also tried:

`brew gem install searchlink` and
`gem install --user-install searchlink`

same error message

**Comment by ttscoff** [comment]
Might be a ruby 3.x issue, rexml is a default library.

**Comment by ttscoff** [comment]
I'll look into it tomorrow.

**Comment by ttscoff** [comment]
Apparently I don't actually use Rexml in the script anymore anyway, so removed that dependency. Tested with Ruby 3.3 and seems to be working. Update to the latest gem (`gem install searchlink`) and let me know.

**Comment by kjaymiller** [comment]
@ttscoff  - yup seems to work!
