### ISSUE TITLE
Wiki: Configuration link on Installation Page 

### ISSUE THREAD

**Issue by miklb** [ttscoff/searchlink#2]
I didn't see a way to suggest the fix directly in the wiki but on [Installation](https://github.com/ttscoff/searchlink/wiki/Installation) it links to `#Configuration`, which I'm assuming is an artifact of it being a single markdown file.

I've seen you post about this in the past but I watched the latest video and it clicked. Brilliant.

**Comment by miklb** [comment]
Also on [Examples](https://github.com/ttscoff/searchlink/wiki/Examples).

**Comment by ttscoff** [comment]
Fixed, thanks for catching that!
