### ISSUE TITLE
FR: configuration should be placed in `.config`

### ISSUE THREAD

**Issue by chrisgrieser** [ttscoff/searchlink#4]
It's more or less a standard that CLIs put their configuration into the `~/.config/cli-name/` folder instead of the home directory. Or alternatively, look in `.config` and if no configuration file is found there, they look in the home directory, as a more backwards compatible solution

plugins could also be placed there, making syncing the full config more convenient

**Comment by ttscoff** [comment]
Agreed. I set up the `~/.searchlink` file a LONG time ago, before I ever saw CLIs organizing in that way. Most of my other tools have adapted to look for both, I'll try to set up SearchLink to do the same soon.

**Comment by ttscoff** [comment]
As far as plugins, I think they make more sense in `~/.local/searchlink/plugins` at this point. But maybe I'm confused about what the `~/.local` directory is commonly used for? It would make sense to consolidate and not be spread across both .local and .config...

**Comment by ttscoff** [comment]
Ok, so everything is now located in ~/.config/searchlink. This makes the most sense, so I've pointed the config, plugins, and cache storage to that directory, all in one place. The old directories/files will still work if the new ones don't exist, and it makes no effort to port old configs to the new one, just allows for that configuration moving forward.
