### ISSUE TITLE
Invoking searchlink on "help" results in an error

### ISSUE THREAD

**Issue by Younghart** [ttscoff/searchlink#7]
The command "help" results in the following error:
 <img width="372" alt="Bildschirmfoto 2024-01-15 um 09 18 02" src="https://github.com/ttscoff/searchlink/assets/2934471/7d5a0d19-b912-467a-a3b0-fb1bc550f912">
So the error message says „-e:856:in ' initialize': No such file or directory @ rb_sysopen - /Users/ immo/.config/cache/update.tt
(Errno::ENOENT) from -e:856:in 'open' from -e:856:in 'version_check' from -e:4700:in 'help_dialog' from -e:4772:in 'parse_commands' from -e:4797:in 'parse' from -e:5900:in '<main>'"

This happened after I manually installed a searchlink update. There was an older searchlink version on this mac mini M1, but I might not have used it yet. I deleted the ~/.config/searchling/cache folder and restarted, but the error reappeared. Invoking "update" tells me that searchlink is up to date.

**Comment by Younghart** [comment]
Just went over to an Intel Mac where the help command still worked, yet wasn't up to date. After the update: same situation. "help" seems to be broken in the current SearchLink version. So it's not device-specific or config-specific.

**Comment by ttscoff** [comment]
Yeah, I moved the cache file and it caused an error. I thought I'd fixed this, though, what version are you on?

**Comment by Younghart** [comment]
I'm not sure, "version" results in an error, too :-D The file itself (SearchLink.service) was from 2024-01-11.
Next, I invoked searchlink on "update". It answered with "Installed SearchLink 2.3.65" - ant then, it was gone. No SearchLink in the Services menu, and it also disappeared from the ~/Library/Services folder. 
But! After a manual re-install, SearchLink 2.3.65 works like a charm. So, yeah, it's fixed.
