### ISSUE TITLE
Allow for multi-line processing

### ISSUE THREAD

**Issue by matru** [ttscoff/searchlink#9]
I couldn't really find a way to process multiple lines in one go. My use case for example might be, while reading articles, discussions and so on, I would be copying names of different products, books, movies or songs, afterwards I would paste them into a text editor and process them there into multi-line splits if they aren't already (using vim/regex, textsoap, popclip extensions and so on). It would then be perfect if I can run a searchlink on all the lines instead of manually doing it one by one, since such lists can easily be 50+ items.

It does seem intuitive that SL would run on all the selected items, so I don't think this can break many people workflows, but if you believe it might, having an additional quick action for multi-line processing (I think better than manually flagging the multi-liners for them to be processed or not) could resolve such confusion.

**Comment by ttscoff** [comment]
That's what the `[](!search)` syntax is for. The single-line (`!search [text]`) syntax can't be easily distinguished from other text. The `![text](!search)` syntax is  contained and you can process an entire document all at once.

**Comment by matru** [comment]
I am not really a user of SL, since the reason I am looking to use it is solely the use case I am asking for, so maybe I am missing something.

Here are three books I want to search on goodreads:

the logic of life
the meaning of it all
freakonomics

I want to just select all this text, run search link for all under goodreads and all of them to be updated to:

https://www.goodreads.com/book/show/1249095.The_Logic_of_Life
https://www.goodreads.com/book/show/17375.The_Meaning_of_It_All
https://www.goodreads.com/book/show/1202.Freakonomics

Or the markdown equivalent based on the original text. This wouldn't work:

[the logic of life
the meaning of it all
freakonomics](!goodreads)

This would work:

[the logic of life]!goodreads)
[the meaning of it all]!goodreads)
[freakonomics](!goodreads)

Is there a way for the first example to work? One way would be to do a multi-line selection, append `[` at the start, and  `](!goodreads)` at the end for each, however this is a bit more tedious.

**Comment by ttscoff** [comment]
There's no way for SearchLink to tell what's a search and what isn't in a multi-line selection. For most use cases, a multi-line search indicates that the searches are mixed in with other syntax and text. Modifying it to work with your use case would break it for everyone else. 

It would be feasible to write a script that handled this automatically, just splitting on newlines and running a search per line, but it's not something built-in or that I plan to accommodate in the main bundle.

You could just select each line individually and run it, but wrapping in syntax is the only way SearchLink will handle multiple lines.

**Comment by ttscoff** [comment]
Your example might be feasible, but SL doesn't currently expect multi-line `[](!)` syntax. I might consider it, but it seems like effort on my part that would actually be minimal effort on your part. Just select each line and hit the shortcut for SL... or create a script that breaks it apart for you...

**Comment by matru** [comment]
I see, thanks. Btw, it's no issue when there are 3 lines, but very often I am processing hundreds. I guess the find and replace method would be the best I got for the time being.

**Comment by ttscoff** [comment]
If you're working in a text editor that allows regex searches (VS Code, 
Sublime, etc.), it would be as simple as:

search: ^(.*?)$
replace: [$1](!g)

But that could be done in a simple script like (ruby below)

```ruby
#!/usr/bin/env ruby

puts $stdin.read.gsub(/^(.*?)$/, '[\1](!g)')
```

That could be run from a Shortcut or service or whatever.

**Comment by matru** [comment]
yep, exactly! Thanks. I will implement it one way or another.

**Comment by ttscoff** [comment]
I changed my mind and implemented this. [See the wiki for instructions](https://github.com/ttscoff/searchlink/wiki/Advanced-Search-Format#multiline-search-syntax). It should fit your use case perfectly.

**Comment by matru** [comment]
marvellous, thank you Brett!
